apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-ui.my-apps.tap.20240307193258.0.0+build.6aff574
spec:
  refName: where-for-dinner-ui.my-apps.tap
  version: 20240307193258.0.0+build.6aff574
  releaseNotes: |
    Release v20240307193258.0.0+build.6aff574 of package where-for-dinner-ui.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tap-ci/ci-pipeline/apps-07-03-2024-00-51-49-026605919/where-for-dinner-ui-my-apps-bundle@sha256:4735e28420d5a04818d8e1ca3599f47fbd133a35ffb498baa3b547fd1d8c47f1
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

