apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner.my-apps.tap.20240307182310.0.0+build.6aff574
spec:
  refName: where-for-dinner.my-apps.tap
  version: 20240307182310.0.0+build.6aff574
  releaseNotes: |
    Release v20240307182310.0.0+build.6aff574 of package where-for-dinner.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tap-ci/ci-pipeline/apps-07-03-2024-00-51-49-026605919/where-for-dinner-my-apps-bundle@sha256:9784e6ef3f8ceed8f92ee5d90273a00f34ffa945e310f9b669f91d96597bc56e
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

